#!/usr/bin/env bash
USERNAME='root'
PASSWORD=''
DBNAME='db_biocoop'
HOST='localhost'

USER_USERNAME='tony'
USER_PASSWORD='tony'

MySQL=$(cat <<EOF
DROP DATABASE IF EXISTS $DBNAME;
CREATE DATABASE $DBNAME DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
DELETE FROM mysql.user WHERE user='$USER_USERNAME' and host='$USER_PASSWORD';
GRANT ALL PRIVILEGES ON $DBNAME.* to '$USER_USERNAME'@'$HOST' IDENTIFIED BY '$USER_PASSWORD' WITH GRANT OPTION;
USE $DBNAME;
CREATE TABLE IF NOT EXISTS products (ID INT NOT NULL AUTO_INCREMENT, name VARCHAR(100), price DECIMAL(5,2), total DECIMAL(5,2) NOT NULL DEFAULT 0.00, PRIMARY KEY(id) )ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
INSERT INTO products (name, price) VALUES  ('apple', 10.5), ('raspberry',13), ('strawberry', 7.8)
EOF
)

echo $MySQL | mysql --user=$USERNAME --password=$PASSWORD